LIBRARIES := ../portability
# comment out the following line to exclude the containers library and un-comment the following line
LIBRARIES += ../containers
#CPPFLAGS += -DNO_STLPLUS_CONTAINERS
include ../../makefiles/gcc.mak
