#!/bin/sh
# Regression test suite
# Runs a set of tests on the STLplus components

echo "##################################################"

passed="0"
failed="0"
root=`pwd`
for dir in *; do
  if [ -d "$dir" ]; then
    if [ "$dir" != "CVS" ]; then
      cd "$dir"
      echo "### testing $dir"
      time "$dir"
      if [ $? -ne 0 ] ; then
        echo "### test of $dir failed"
        failed=`expr $failed + 1`
      else
        passed=`expr $passed + 1`
      fi
      echo "##################################################"
      cd "$root"
    fi
  fi
done

echo "Passed : $passed"
echo "Failed : $failed"
echo "##################################################"
exit $failed
