mkdir BORLAND-i686-debug
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\build.obj build.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\cli_parser.obj cli_parser.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\debug.obj debug.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\dprintf.obj dprintf.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\dynaload.obj dynaload.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\file_system.obj file_system.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\inf.obj inf.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\ini_manager.obj ini_manager.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\ip_sockets.obj ip_sockets.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\library_manager.obj library_manager.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\message_handler.obj message_handler.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_bool.obj persistent_bool.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_contexts.obj persistent_contexts.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_cstring.obj persistent_cstring.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_exceptions.obj persistent_exceptions.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_float.obj persistent_float.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_inf.obj persistent_inf.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_int.obj persistent_int.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_string.obj persistent_string.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\persistent_vector.obj persistent_vector.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\portability_fixes.obj portability_fixes.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_address.obj print_address.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_bool.obj print_bool.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_cstring.obj print_cstring.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_float.obj print_float.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_inf.obj print_inf.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_int.obj print_int.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_string.obj print_string.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\print_vector.obj print_vector.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_address.obj string_address.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_bool.obj string_bool.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_cstring.obj string_cstring.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_float.obj string_float.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_inf.obj string_inf.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_int.obj string_int.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_string.obj string_string.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_utilities.obj string_utilities.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\string_vector.obj string_vector.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\subprocesses.obj subprocesses.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\tcp_sockets.obj tcp_sockets.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\time.obj time.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\timer.obj timer.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\udp_sockets.obj udp_sockets.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\version.obj version.cpp
bcc32 -c +..\bcc.cfg -oBORLAND-i686-debug\wildcard.obj wildcard.cpp
del /Q "BORLAND-i686-debug\stlplus3.lib"
tlib "BORLAND-i686-debug\stlplus3.lib" /a   "BORLAND-i686-debug\build.obj"   "BORLAND-i686-debug\cli_parser.obj"   "BORLAND-i686-debug\debug.obj"   "BORLAND-i686-debug\dprintf.obj"   "BORLAND-i686-debug\dynaload.obj"   "BORLAND-i686-debug\file_system.obj"   "BORLAND-i686-debug\inf.obj"   "BORLAND-i686-debug\ini_manager.obj"   "BORLAND-i686-debug\ip_sockets.obj"   "BORLAND-i686-debug\library_manager.obj"   "BORLAND-i686-debug\message_handler.obj"   "BORLAND-i686-debug\persistent_bool.obj"   "BORLAND-i686-debug\persistent_contexts.obj"   "BORLAND-i686-debug\persistent_cstring.obj"   "BORLAND-i686-debug\persistent_exceptions.obj"   "BORLAND-i686-debug\persistent_float.obj"   "BORLAND-i686-debug\persistent_inf.obj"   "BORLAND-i686-debug\persistent_int.obj"   "BORLAND-i686-debug\persistent_string.obj"   "BORLAND-i686-debug\persistent_vector.obj"   "BORLAND-i686-debug\portability_fixes.obj"   "BORLAND-i686-debug\print_address.obj"   "BORLAND-i686-debug\print_bool.obj"   "BORLAND-i686-debug\print_cstring.obj"   "BORLAND-i686-debug\print_float.obj"   "BORLAND-i686-debug\print_inf.obj"   "BORLAND-i686-debug\print_int.obj"   "BORLAND-i686-debug\print_string.obj"   "BORLAND-i686-debug\print_vector.obj"   "BORLAND-i686-debug\string_address.obj"   "BORLAND-i686-debug\string_bool.obj"   "BORLAND-i686-debug\string_cstring.obj"   "BORLAND-i686-debug\string_float.obj"   "BORLAND-i686-debug\string_inf.obj"   "BORLAND-i686-debug\string_int.obj"   "BORLAND-i686-debug\string_string.obj"   "BORLAND-i686-debug\string_utilities.obj"   "BORLAND-i686-debug\string_vector.obj"   "BORLAND-i686-debug\subprocesses.obj"   "BORLAND-i686-debug\tcp_sockets.obj"   "BORLAND-i686-debug\time.obj"   "BORLAND-i686-debug\timer.obj"   "BORLAND-i686-debug\udp_sockets.obj"   "BORLAND-i686-debug\version.obj"   "BORLAND-i686-debug\wildcard.obj"
