#!/bin/sh
################################################################################
# utility for building colourised HTML from the headers
for d in containers persistence portability strings subsystems; do
  for f in ../$d/*.hpp; do
    hpp_file=$f
    html_file=`basename $hpp_file .hpp`_hpp.html
    if [ "$hpp_file" -nt "$html_file" ]; then
      title=`basename \`dirname "$hpp_file"\``/`basename $hpp_file`
      echo "$hpp_file => $html_file ($title)"
      ccolour -noversion -html -nortf -linenumbers -title "$title" "$hpp_file"
    fi
  done
done
